pipeline:
  build:
    image: python:${PYTHON_VERSION}-alpine
    commands:
      - pip install -r requirements.txt
      - pip install -r test_requirements.txt
      - python tests/interface_test.py


  slack:
    image: plugins/slack
    webhook: ${WEBHOOK}
    channel: ${CHANNEL}

matrix:
  PYTHON_VERSION:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

branches: [ master, feature/* ]